name: Update Top 10

on:
  schedule:
    - cron: "0 5 * * *"   # Mise à jour tous les jours à 5h du matin
  workflow_dispatch:      # Permet de lancer manuellement

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        npm install node-fetch@2

    - name: Run scraper
      env:
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        RPDB_API_KEY: ${{ secrets.RPDB_API_KEY }}
      run: node scraper.js

    - name: Commit updated JSON
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add data/*.json
        git commit -m "Updated JSON files" || echo "No changes to commit"
        git push
